<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXODz5rU\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXODz5rU/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXODz5rU.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXODz5rU\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXODz5rU\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XODz5rU',
    'container.build_id' => '93b90b8c',
    'container.build_time' => 1616408970,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXODz5rU');
